# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2026-Present Datadog, Inc.

"""Integration tests for the HTTP proxy.

The proxy is per-agent: every handler declares its own ``upstream()`` and
claims requests via ``matches()`` (User-Agent only). There is no default
upstream — a request no handler claims gets 502.

Grouped by what's being exercised:

  * :class:`TestProxyPassthrough` — Claude requests claimed by ``ClaudeProxy``
    are forwarded to its upstream and persisted to storage. Includes the
    "matches() is UA-only" edge case (off-path Claude UA still matches).
  * :class:`TestProxyStreaming` — SSE responses pass through byte-for-byte
    while the assistant message is reconstructed and stored.
  * :class:`TestProxyUnclaimed` — no handler claims the request → 502.
  * :class:`TestProxyMultiHandler` — multiple handlers, each with its own
    upstream; first matching handler wins; hooks dispatch by agent segment.
  * :class:`TestProxyHookRouting` — ``/hook/<agent>/<hook>`` URL dispatch
    (User-Agent contains ``ai-guard-cli``).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import aiohttp
import aiohttp.web
import pytest
from aiohttp.test_utils import TestServer

from aiguard import storage
from aiguard.proxy.server import Proxy, ProxyHandler

CLAUDE_UA = "claude-cli/1.2.3 (External, cli)"
HOOK_UA = "ai-guard-cli/test"
FIXTURE_SSE = Path(__file__).resolve().parents[1] / "fixtures" / "anthropic_sse_stream.txt"


# ── Passthrough + storage ─────────────────────────────────────────────────────


def _anthropic_handler(response_body: dict[str, Any]) -> Any:
    async def handler(request: aiohttp.web.Request) -> aiohttp.web.Response:
        return aiohttp.web.json_response(response_body)

    return handler


class TestProxyPassthrough:
    async def test_returns_upstream_body_and_persists_messages(
        self,
        proxy_client,
        storage_root: Path,
        anthropic_request_body: dict[str, Any],
        anthropic_response_body: dict[str, Any],
    ) -> None:
        client = await proxy_client(_anthropic_handler(anthropic_response_body))

        async with client.post(
            "/v1/messages",
            json=anthropic_request_body,
            headers={"User-Agent": CLAUDE_UA, "x-api-key": "sk-test"},
        ) as resp:
            assert resp.status == 200
            body = await resp.json()
            assert body["id"] == anthropic_response_body["id"]

        # Session id is embedded in metadata.user_id JSON in the request body.
        stored = storage.load_messages("claude", "sess-abc")
        roles = [m["role"] for m in stored]
        assert roles[0] == "system"
        assert "assistant" in roles
        assert stored[-1]["role"] == "assistant"

    async def test_strips_hop_by_hop_request_headers(
        self,
        proxy_client,
        anthropic_request_body: dict[str, Any],
        anthropic_response_body: dict[str, Any],
        storage_root: Path,
    ) -> None:
        """Headers in ``_SKIP_REQ_HEADERS`` (host, content-length,
        transfer-encoding) must not be forwarded verbatim — aiohttp regenerates
        them for the upstream connection. Auth headers like ``x-api-key`` must
        survive the hop.
        """
        seen_headers: dict[str, str] = {}
        proxy_host_header = "the-proxys-public-name.invalid"

        async def handler(request: aiohttp.web.Request) -> aiohttp.web.Response:
            seen_headers.update(dict(request.headers))
            return aiohttp.web.json_response(anthropic_response_body)

        client = await proxy_client(handler)
        body = json.dumps(anthropic_request_body).encode()
        async with client.post(
            "/v1/messages",
            data=body,
            headers={
                "User-Agent": CLAUDE_UA,
                "Content-Type": "application/json",
                "x-api-key": "kept",
                # A bogus Host the client thinks it's reaching — must NOT
                # survive the hop; aiohttp regenerates Host for the upstream.
                "Host": proxy_host_header,
            },
        ) as resp:
            assert resp.status == 200

        lower = {k.lower(): v for k, v in seen_headers.items()}

        # Auth header survives.
        assert lower.get("x-api-key") == "kept"

        # Host is regenerated by aiohttp to point at the upstream — the
        # client-provided Host MUST NOT leak to the upstream.
        assert lower.get("host") != proxy_host_header

        # Content-Length is regenerated by aiohttp from the actual body. The
        # client-supplied bytes are intact upstream (length matches body).
        assert lower.get("content-length") == str(len(body))

    async def test_request_replaces_then_response_appends(
        self,
        proxy_client,
        storage_root: Path,
        anthropic_request_body: dict[str, Any],
        anthropic_response_body: dict[str, Any],
    ) -> None:
        """Two realistic turns: every request carries the full history (Anthropic
        Messages API is stateless), the proxy replaces on request and appends on
        response — no duplication."""

        async def handler(request: aiohttp.web.Request) -> aiohttp.web.Response:
            return aiohttp.web.json_response(anthropic_response_body)

        client = await proxy_client(handler)

        # Turn 1
        async with client.post(
            "/v1/messages",
            json=anthropic_request_body,
            headers={"User-Agent": CLAUDE_UA},
        ):
            pass

        after_turn1 = storage.load_messages("claude", "sess-abc")
        assert after_turn1
        assert after_turn1[-1]["role"] == "assistant"

        # Turn 2: client adds the assistant reply from turn 1 plus a new user prompt.
        turn2_body = {
            **anthropic_request_body,
            "messages": [
                *anthropic_request_body["messages"],
                {
                    "role": "assistant",
                    "content": [{"type": "text", "text": "All done."}],
                },
                {"role": "user", "content": "Anything else?"},
            ],
        }
        async with client.post(
            "/v1/messages",
            json=turn2_body,
            headers={"User-Agent": CLAUDE_UA},
        ):
            pass

        after_turn2 = storage.load_messages("claude", "sess-abc")
        # Expected: prior history (replaced from turn-2 request body) + new response.
        assert len(after_turn2) == len(after_turn1) + 2
        assert after_turn2[-1]["role"] == "assistant"
        # The "Anything else?" prompt from turn 2's request is present exactly once.
        user_texts = [m for m in after_turn2 if m.get("role") == "user"]
        assert sum(1 for m in user_texts if "Anything else?" in str(m.get("content", ""))) == 1

    async def test_claude_ua_with_off_path_still_forwards_upstream(
        self, proxy_client, anthropic_response_body, storage_root: Path
    ) -> None:
        """``ClaudeProxy.matches()`` is User-Agent only — method, path, and
        content-type are ``parse_request``'s concern. So a Claude UA with an
        off-spec path still gets claimed and forwarded; ``parse_request`` then
        returns no messages, so nothing is persisted."""

        async def handler(request: aiohttp.web.Request) -> aiohttp.web.Response:
            return aiohttp.web.json_response(anthropic_response_body)

        client = await proxy_client(handler)
        async with client.get("/v1/anything", headers={"User-Agent": CLAUDE_UA}) as resp:
            assert resp.status == 200

        assert not storage_root.exists() or not any(storage_root.rglob("*.json"))


# ── Streaming ────────────────────────────────────────────────────────────────


class TestProxyStreaming:
    async def test_streaming_passthrough_persists_assistant_message(
        self,
        proxy_client,
        storage_root: Path,
        anthropic_request_body: dict[str, Any],
    ) -> None:
        sse_body = FIXTURE_SSE.read_bytes()

        async def handler(request: aiohttp.web.Request) -> aiohttp.web.StreamResponse:
            resp = aiohttp.web.StreamResponse(
                status=200, headers={"Content-Type": "text/event-stream"}
            )
            await resp.prepare(request)
            mid = len(sse_body) // 2
            await resp.write(sse_body[:mid])
            await resp.write(sse_body[mid:])
            await resp.write_eof()
            return resp

        streamed = {**anthropic_request_body, "stream": True}
        client = await proxy_client(handler)
        async with client.post(
            "/v1/messages",
            json=streamed,
            headers={"User-Agent": CLAUDE_UA},
        ) as resp:
            assert resp.status == 200
            assert await resp.read() == sse_body

        stored = storage.load_messages("claude", "sess-abc")
        assistants = [m for m in stored if m.get("role") == "assistant"]
        assert assistants, "expected reconstructed assistant message in storage"
        last = assistants[-1]
        text_part = next((p for p in last.get("content", []) if p["type"] == "text"), None)
        assert text_part is not None
        assert text_part["text"] == "Hello world"
        tool_call = last.get("tool_calls", [])[0]
        assert tool_call["function"]["name"] == "Read"
        assert json.loads(tool_call["function"]["arguments"]) == {"path": "README.md"}


# ── Unclaimed traffic ─────────────────────────────────────────────────────────


class TestProxyUnclaimed:
    """The proxy is per-agent: each handler declares its own ``upstream()`` and
    claims requests via ``matches()``. There is no default upstream — when no
    registered handler claims a request, the proxy returns **502**. The body
    explains why, and no upstream is contacted."""

    @staticmethod
    def _unreachable_upstream(_: object):
        async def handler(request: aiohttp.web.Request) -> aiohttp.web.Response:
            raise AssertionError("upstream must not be hit when no handler claims the request")

        return handler

    @staticmethod
    def _assert_no_storage(storage_root: Path) -> None:
        assert not storage_root.exists() or not any(storage_root.rglob("*.json"))

    async def test_unknown_ua_returns_502(self, proxy_client, storage_root: Path) -> None:
        client = await proxy_client(self._unreachable_upstream(None))

        async with client.get("/v1/health", headers={"User-Agent": "curl/8.0"}) as resp:
            assert resp.status == 502
            # Lock in the body contract: the proxy explains why it dropped the
            # request, citing method + path. A future change that swaps the
            # status without an explanation should fail this assertion.
            assert "no handler claims" in (await resp.text())

        self._assert_no_storage(storage_root)

    async def test_no_ua_returns_502(self, proxy_client, storage_root: Path) -> None:
        client = await proxy_client(self._unreachable_upstream(None))

        async with client.post("/v1/messages", data=b"raw") as resp:
            assert resp.status == 502
            assert "no handler claims" in (await resp.text())

        self._assert_no_storage(storage_root)


# ── Multiple handlers ────────────────────────────────────────────────────────


class _StubHandler(ProxyHandler):
    """Routing-test stub. ``matches()`` returns True iff the configured UA
    substring is present; ``parse_request`` / ``parse_response`` are no-ops so
    storage stays empty (these tests check routing, not persistence).
    """

    def __init__(
        self,
        agent: str,
        upstream: str,
        ua_substring: str,
        hook_reply: bytes = b"",
    ) -> None:
        self._agent = agent
        self._upstream = upstream
        self._ua_substring = ua_substring
        self._hook_reply = hook_reply
        self.hook_calls: list[tuple[str, bytes]] = []

    def agent(self) -> str:
        return self._agent

    def upstream(self) -> str:
        return self._upstream

    def matches(self, request: aiohttp.web.Request) -> bool:
        return self._ua_substring in request.headers.get("User-Agent", "")

    def parse_request(self, request: aiohttp.web.Request, body: bytes):
        return "", []

    def parse_response(self, response: aiohttp.ClientResponse, body: bytes):
        return []

    async def handle_hook(self, hook: str, payload: bytes) -> bytes:
        self.hook_calls.append((hook, payload))
        return self._hook_reply


@pytest.fixture
async def multi_handler_proxy() -> Any:
    """Yield a factory that wires a proxy in front of an arbitrary handler list.

    Each handler keeps the upstream URL it was constructed with — the proxy
    has no global upstream to fall back on. Tests pass real upstream URLs
    (built via ``anthropic_server``) for routing assertions, or sentinel
    ``http://invalid.example`` URLs when only the hook path is exercised.
    """
    servers: list[TestServer] = []

    async def factory(
        handlers: list[_StubHandler],
    ) -> aiohttp.test_utils.TestClient:
        proxy = Proxy(host="127.0.0.1", port=0, handlers=list(handlers))
        app = proxy.build_app()
        server = TestServer(app)
        await server.start_server()
        servers.append(server)
        client = aiohttp.test_utils.TestClient(server)
        await client.start_server()
        return client

    yield factory

    for s in servers:
        await s.close()


class TestProxyMultiHandler:
    """The per-agent contract with ≥2 handlers wired into the same proxy:

    * Each handler routes its claimed traffic to its **own** ``upstream()``
      — siblings' upstreams are never called.
    * When two handlers' ``matches()`` both return True, the **first** one
      in the handler list wins.
    * Hook traffic is dispatched by the **agent segment** in the URL
      (``/hook/<agent>/<hook>``), not by ``matches()`` and not by list
      order.
    """

    @staticmethod
    async def _marker_upstream(anthropic_server_factory, marker: str) -> str:
        """Boot a tiny upstream that echoes ``marker`` so the test can
        verify which upstream the proxy actually contacted."""

        async def handler(request: aiohttp.web.Request) -> aiohttp.web.Response:
            return aiohttp.web.json_response({"upstream": marker})

        return await anthropic_server_factory(handler)

    async def test_each_handler_routes_to_its_own_upstream(
        self,
        anthropic_server,
        multi_handler_proxy,
        storage_root: Path,
    ) -> None:
        url_alpha = await self._marker_upstream(anthropic_server, "alpha")
        url_beta = await self._marker_upstream(anthropic_server, "beta")
        client = await multi_handler_proxy(
            [
                _StubHandler(agent="alpha", upstream=url_alpha, ua_substring="alpha-cli"),
                _StubHandler(agent="beta", upstream=url_beta, ua_substring="beta-cli"),
            ]
        )

        async with client.post("/x", headers={"User-Agent": "alpha-cli/1.0"}) as resp:
            assert resp.status == 200
            assert (await resp.json()) == {"upstream": "alpha"}

        async with client.post("/x", headers={"User-Agent": "beta-cli/1.0"}) as resp:
            assert resp.status == 200
            assert (await resp.json()) == {"upstream": "beta"}

    async def test_first_matching_handler_wins(
        self,
        anthropic_server,
        multi_handler_proxy,
        storage_root: Path,
    ) -> None:
        url_first = await self._marker_upstream(anthropic_server, "first")
        url_second = await self._marker_upstream(anthropic_server, "second")
        # Both handlers claim the same UA — list order decides.
        client = await multi_handler_proxy(
            [
                _StubHandler(agent="first", upstream=url_first, ua_substring="cli/"),
                _StubHandler(agent="second", upstream=url_second, ua_substring="cli/"),
            ]
        )

        async with client.post("/x", headers={"User-Agent": "any-cli/1.0"}) as resp:
            assert resp.status == 200
            assert (await resp.json()) == {"upstream": "first"}

    async def test_hook_dispatches_by_agent_segment_not_list_order(
        self,
        multi_handler_proxy,
        storage_root: Path,
    ) -> None:
        # Both handlers' matches() return False (sentinel UA never appears),
        # so proxy traffic would 502; this test only exercises the hook path.
        h_alpha = _StubHandler(
            agent="alpha",
            upstream="http://invalid.example",
            ua_substring="never",
            hook_reply=b'{"r": "alpha"}',
        )
        h_beta = _StubHandler(
            agent="beta",
            upstream="http://invalid.example",
            ua_substring="never",
            hook_reply=b'{"r": "beta"}',
        )
        client = await multi_handler_proxy([h_alpha, h_beta])

        async with client.post(
            "/hook/beta/session-start",
            data=b'{"x": 1}',
            headers={"User-Agent": HOOK_UA},
        ) as resp:
            assert resp.status == 200
            assert (await resp.json()) == {"r": "beta"}

        assert h_alpha.hook_calls == []
        assert h_beta.hook_calls == [("session-start", b'{"x": 1}')]


# ── Hook URL routing ─────────────────────────────────────────────────────────


class _RecordingHandler(ProxyHandler):
    """Minimal handler that records hook invocations and returns canned bytes."""

    def __init__(self, agent_name: str = "claude", reply: bytes = b"") -> None:
        self._agent = agent_name
        self._reply = reply
        self.calls: list[tuple[str, bytes]] = []
        self.fail = False

    def agent(self) -> str:
        return self._agent

    def upstream(self) -> str:
        return "http://upstream.invalid"

    def matches(self, request: aiohttp.web.Request) -> bool:
        return False

    def parse_request(self, request: aiohttp.web.Request, body: bytes):
        return "", []

    def parse_response(self, response: aiohttp.ClientResponse, body: bytes):
        return []

    async def handle_hook(self, hook: str, payload: bytes) -> bytes:
        self.calls.append((hook, payload))
        if self.fail:
            raise RuntimeError("boom")
        return self._reply


@pytest.fixture
async def hook_proxy() -> Any:
    """Proxy harness pre-wired with a recording handler. Yields ``factory``."""
    servers: list[TestServer] = []

    async def factory(
        agent: str = "claude", reply: bytes = b""
    ) -> tuple[aiohttp.test_utils.TestClient, _RecordingHandler]:
        handler = _RecordingHandler(agent, reply)
        proxy = Proxy(
            host="127.0.0.1",
            port=0,
            handlers=[handler],
        )
        app = proxy.build_app()
        server = TestServer(app)
        await server.start_server()
        servers.append(server)
        client = aiohttp.test_utils.TestClient(server)
        await client.start_server()
        return client, handler

    yield factory

    for s in servers:
        await s.close()


class TestProxyHookRouting:
    """The proxy routes to ``_handle_hook`` when the User-Agent contains
    ``ai-guard-cli`` (set by the ``ai-guard hook`` CLI). Without that UA the
    request goes through ``_handle_proxy`` instead — so every test here sets
    ``User-Agent: ai-guard-cli/test`` to opt into the hook path."""

    async def test_routes_to_handler_by_agent(self, hook_proxy) -> None:
        client, handler = await hook_proxy(agent="claude", reply=b'{"ok": true}')

        async with client.post(
            "/hook/claude/session-start",
            data=b'{"session_id": "s1"}',
            headers={"User-Agent": HOOK_UA, "Content-Type": "application/json"},
        ) as resp:
            assert resp.status == 200
            assert resp.content_type == "application/json"
            assert await resp.read() == b'{"ok": true}'

        assert handler.calls == [("session-start", b'{"session_id": "s1"}')]

    async def test_empty_response_returns_204(self, hook_proxy) -> None:
        client, handler = await hook_proxy(agent="claude", reply=b"")

        async with client.post(
            "/hook/claude/session-end",
            data=b'{"reason": "logout"}',
            headers={"User-Agent": HOOK_UA},
        ) as resp:
            assert resp.status == 204
            assert await resp.read() == b""

        assert handler.calls == [("session-end", b'{"reason": "logout"}')]

    async def test_unknown_agent_returns_404(self, hook_proxy) -> None:
        client, handler = await hook_proxy(agent="claude")

        async with client.post(
            "/hook/codex/session-start", data=b"{}", headers={"User-Agent": HOOK_UA}
        ) as resp:
            assert resp.status == 404

        assert handler.calls == []

    async def test_missing_hook_segment_returns_404(self, hook_proxy) -> None:
        client, _ = await hook_proxy(agent="claude")

        async with client.post("/hook/claude", data=b"{}", headers={"User-Agent": HOOK_UA}) as resp:
            assert resp.status == 404

    async def test_root_path_returns_404(self, hook_proxy) -> None:
        client, _ = await hook_proxy()

        async with client.post("/hook", data=b"", headers={"User-Agent": HOOK_UA}) as resp:
            assert resp.status == 404

    async def test_nested_name_passed_through(self, hook_proxy) -> None:
        client, handler = await hook_proxy(agent="claude", reply=b"")

        async with client.post(
            "/hook/claude/sub/agent-start",
            data=b'{"x": 1}',
            headers={"User-Agent": HOOK_UA},
        ):
            pass

        assert handler.calls == [("sub/agent-start", b'{"x": 1}')]

    async def test_handler_exception_returns_500(
        self, hook_proxy, caplog: pytest.LogCaptureFixture
    ) -> None:
        client, handler = await hook_proxy(agent="claude")
        handler.fail = True

        async with client.post(
            "/hook/claude/session-start", data=b"{}", headers={"User-Agent": HOOK_UA}
        ) as resp:
            assert resp.status == 500

        assert handler.calls == [("session-start", b"{}")]
        assert any("hook failed" in rec.message for rec in caplog.records)

    async def test_query_string_stripped(self, hook_proxy) -> None:
        client, handler = await hook_proxy(agent="claude")

        async with client.post(
            "/hook/claude/session-start?trace=1",
            data=b"{}",
            headers={"User-Agent": HOOK_UA},
        ) as resp:
            assert resp.status == 204

        assert handler.calls == [("session-start", b"{}")]


# ── Idle-timeout shutdown ─────────────────────────────────────────────────────


class TestProxyIdleTimeout:
    """``Proxy(idle_timeout=...)`` exits the run loop after N quiet seconds.

    The init systems (launchd ``Sockets``, systemd ``.socket``) re-launch on
    the next connection — we just have to make sure ``run()`` returns cleanly
    and that an in-flight request keeps the timer fresh.
    """

    async def test_zero_timeout_blocks_forever(self) -> None:
        """``idle_timeout=0`` is the "stay up" mode used in interactive sessions."""
        import asyncio

        proxy = Proxy(host="127.0.0.1", port=0, handlers=[], idle_timeout=0.0)
        # _serve_until_idle should never return on its own — assert it stays
        # blocked across a generous wait window.
        with pytest.raises(asyncio.TimeoutError):
            await asyncio.wait_for(proxy._serve_until_idle(), timeout=0.2)

    async def test_returns_after_quiet_window(self) -> None:
        """No traffic for ``idle_timeout`` seconds → ``_serve_until_idle`` returns."""
        import time

        proxy = Proxy(host="127.0.0.1", port=0, handlers=[], idle_timeout=0.1)
        start = time.monotonic()
        await proxy._serve_until_idle()
        elapsed = time.monotonic() - start
        # Should exit promptly once the idle window elapses (we allow a wide
        # upper bound to absorb CI slowness).
        assert 0.05 <= elapsed < 2.0

    async def test_active_requests_block_shutdown(self) -> None:
        """An in-flight request prevents idle exit even past the timeout.

        We bump ``_active_requests`` to simulate a long-running stream: the
        watcher must keep waiting until the request count drops back to zero.
        """
        import asyncio
        import time

        proxy = Proxy(host="127.0.0.1", port=0, handlers=[], idle_timeout=0.1)
        proxy._active_requests = 1

        async def release_after(delay: float) -> None:
            await asyncio.sleep(delay)
            proxy._active_requests = 0
            proxy._last_activity = time.monotonic()

        # Kick the request "release" task and time how long shutdown takes.
        # It must NOT exit during the 0.3s the request is pretending to run.
        watcher = asyncio.create_task(proxy._serve_until_idle())
        releaser = asyncio.create_task(release_after(0.3))
        start = time.monotonic()
        try:
            await asyncio.wait_for(watcher, timeout=2.0)
        finally:
            await releaser
        elapsed = time.monotonic() - start
        assert elapsed >= 0.3

    async def test_middleware_refreshes_activity(
        self, proxy_client, anthropic_response_body
    ) -> None:
        """Every request resets ``_last_activity`` so an active session never times out."""
        import time

        async def upstream(request: aiohttp.web.Request) -> aiohttp.web.Response:
            return aiohttp.web.json_response(anthropic_response_body)

        client = await proxy_client(upstream)
        # ``proxy_client`` builds the server with a default proxy; reach into
        # the app for the underlying Proxy instance via the middleware closure.
        # Easier: just check the recorded last_activity moves across calls.
        proxy = client.server.app.middlewares[0].__self__  # type: ignore[attr-defined]
        before = proxy._last_activity
        # Wait long enough that monotonic() will produce a strictly newer value.
        import asyncio

        await asyncio.sleep(0.01)
        async with client.post(
            "/v1/messages",
            json={},
            headers={"User-Agent": CLAUDE_UA, "x-api-key": "k"},
        ) as resp:
            await resp.read()
        after = proxy._last_activity
        assert after > before
        assert after <= time.monotonic()


# ── Socket activation handshake ───────────────────────────────────────────────


class TestProxyInheritedSocket:
    """Smoke-test the launchd / systemd FD-passing path used in production."""

    async def test_uses_systemd_listen_fds_protocol(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """When ``LISTEN_FDS`` / ``LISTEN_PID`` are set, the proxy adopts FDs 3..3+N.

        This is the contract systemd's ``.socket`` unit hands the service:
        the listener is pre-bound by the init system and inherited at fd 3.
        We don't need a real socket — only that the parsing returns the
        expected fd range.
        """
        import os
        import socket as socket_mod

        from aiguard import utils
        from aiguard.proxy import server as proxy_module

        # Force the linux branch so the test is platform-agnostic.
        monkeypatch.setattr(utils, "is_linux", lambda: True)
        monkeypatch.setattr(utils, "is_macos", lambda: False)

        # Build two real sockets so the fileno path returns valid descriptors,
        # but verify ``_inherited_sockets`` reaches for the right env vars.
        s1 = socket_mod.socket(socket_mod.AF_INET, socket_mod.SOCK_STREAM)
        s2 = socket_mod.socket(socket_mod.AF_INET, socket_mod.SOCK_STREAM)
        try:
            monkeypatch.setenv("LISTEN_PID", str(os.getpid()))
            monkeypatch.setenv("LISTEN_FDS", "2")

            captured: list[int] = []
            real_socket = socket_mod.socket

            def fake_socket(*args, **kwargs):
                fileno = kwargs.get("fileno")
                if fileno is not None:
                    captured.append(fileno)
                    # Hand back a throwaway socket so we don't actually
                    # adopt the real fd 3/4 of the test runner.
                    return real_socket()
                return real_socket(*args, **kwargs)

            monkeypatch.setattr(proxy_module.socket, "socket", fake_socket)

            socks = proxy_module._inherited_sockets()
            assert len(socks) == 2
            assert captured == [3, 4]
        finally:
            s1.close()
            s2.close()

    async def test_pid_mismatch_ignored(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """``LISTEN_PID`` set to a different pid means the env vars aren't for us."""
        from aiguard import utils
        from aiguard.proxy import server as proxy_module

        monkeypatch.setenv("LISTEN_PID", "99999")
        monkeypatch.setenv("LISTEN_FDS", "1")
        # Force the linux branch so the test is platform-agnostic.
        monkeypatch.setattr(utils, "is_linux", lambda: True)
        monkeypatch.setattr(utils, "is_macos", lambda: False)
        assert proxy_module._inherited_sockets() == []
